name: cifar10_autotuning_deepspeed
debug: false
hyperparameters:
  deepspeed_config: ds_config.json
environment:
    environment_variables:                                                                          
        - NCCL_DEBUG=INFO                                                                           
        # You may need to modify this to match your network configuration.                          
        - NCCL_SOCKET_IFNAME=ens,eth,ib
    #    - CUDA_LAUNCH_BLOCKING=1
    #    - NCCL_BLOCKING_WAIT=1
    #    - NCCL_IB_DISABLE=1
resources:
  slots_per_trial: 2
records_per_epoch: 50000
searcher:
  name: single
  metric: accuracy
  smaller_is_better: false
  max_length:
    epochs: 2
entrypoint:
  - python3
  - -m
  - determined.launch.deepspeed
  - --autotuning
  - --trial
  - model_def:CIFARTrial
checkpoint_policy: none
max_restarts: 0
scheduling_unit: 2000
